---
version: '3.9'
services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    command: '-conf /etc/coredns/Corefile'
    restart: unless-stopped
    expose:
      - '53'
      - 53/udp
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./config/coredns:/etc/coredns
    networks:
      moonlab:
        ipv4_address: 172.20.0.2
  echo:
    image: ealen/echo-server:latest
    ports:
      - 80:80
    networks:
      moonlab:
        ipv4_address: 172.20.0.3

networks:
  moonlab:
    ipam:
      config:
        - subnet: 172.20.0.0/16