---
version: '3.9'
services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    command: '-conf /etc/coredns/Corefile'
    restart: unless-stopped
    expose:
      - '53'
      - 53/udp
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./config/coredns:/etc/coredns
    networks:
      moonlab:
  chamber:
    image: ealen/echo-server:latest
    container_name: chamber
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      moonlab:

networks:
  moonlab:
    driver: bridge